### ISSUE TITLE
@AndroidViewHolder bombs out if layout has a CardView in it

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#64]
```
Caused
   by: java.lang.RuntimeException: Stub!
	at android.graphics.RectF.<init>(RectF.java:5)
	at
   android.support.v7.widget.CardViewEclairMr1.<init>(CardViewEclairMr1.java:27)
	at
   android.support.v7.widget.CardView.<clinit>(CardView.java:80)
	at
   java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at
   org.xtendroid.utils.AnnotationLayoutUtils.getFieldType(AnnotationLayoutUtils.xtend:23)
	at
   org.xtendroid.utils.AnnotationLayoutUtils.addLazyGetter(AnnotationLayoutUtils.xtend:55)
```

**Comment by tobykurien** [comment]
For now, CardView instances are ignored.
