### ISSUE TITLE
First compile always results in this error

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#74]
Hey @oehme perhaps you can help me with this issue. If you check out the https://github.com/tobykurien/XtendApp project, do a ```gradle clean```, then ```gradle assembleDebug```, it always results in this error:

```
ERROR: 	MainActivity.xtend - 
17: Error during annotation processing:
java.lang.NoClassDefFoundError: android/support/v4/widget/DrawerLayoutImpl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at org.xtendroid.utils.AnnotationLayoutUtils.getFieldType(AnnotationLayoutUtils.xtend:27)
```

This happens on all projects using Xtendroid and the gradle Xtend plugin. If you run ```gradle assembleDebug``` again, it successfully builds the app the second time around. The problem re-appears if you ```gradle clean``` again.

**Comment by oehme** [comment]
A more self-contained example would be welcome. 
I tried adding `com.jakewharton.sdkmanager:gradle-plugin:0.12.+`, which downloads the SDK, but still the build fails, because it cannot find the appCompat library. Can you please adapt this example so it will start compiling without any further setup?

**Comment by tobykurien** [comment]
AppCompat is already added as a dependency in ```app/build.gradle```. It really should compile with no setup needed, other than a ```local.properties``` file pointing to your SDK location.

**Comment by oehme** [comment]
That's what I meant, I don't have an SDK location, the build should manage that automatically.

**Comment by tobykurien** [comment]
I think I see the problem. The appcompat library is installed in a local maven repository as part of the android SDK installation. I don't know how ```com.jakewharton.sdkmanager:gradle-plugin``` handles things, but essentially, you have to run the SDK manager tool from ```sdk-dir/tools/android``` to download and install the *Android Support Repository* and *Android Support Library*. Then the gradle build will work. I do get your point that it should *just work*, but I'm not sure how to set that up - a local installed Android SDK is a pre-requisite with most android projects.

**Comment by tobykurien** [comment]
Perhaps this bug is relevant to you: https://github.com/JakeWharton/sdk-manager-plugin/issues/10

**Comment by oehme** [comment]
I see, so according to that bug it should work on the second try. I'll look
if that helps. thanks for the pointer =)

2015-04-01 12:31 GMT+02:00 Toby Kurien <notifications@github.com>:
