### ISSUE TITLE
Could not initialize class android.support.v7.widget.CardView

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#80]
Seems like CardView is still causing problems with the active annotations:

```
21: Error during annotation processing:
java.lang.NoClassDefFoundError: Could not initialize class android.support.v7.widget.CardView
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.xtendroid.utils.AnnotationLayoutUtils.getFieldType(AnnotationLayoutUtils.java:53)
	at org.xtendroid.utils.AnnotationLayoutUtils.addLazyGetter(AnnotationLayoutUtils.java:139)
	at org.xtendroid.utils.AnnotationLayoutUtils$4.apply(AnnotationLayoutUtils.java:357)
	at org.xtendroid.utils.AnnotationLayoutUtils$4.apply(AnnotationLayoutUtils.java:337)
	at org.xtendroid.utils.XmlUtils.traverseAllNodes(XmlUtils.java:35)
	at org.xtendroid.utils.XmlUtils.traverseAllNodes(XmlUtils.java:31)
	at org.xtendroid.utils.AnnotationLayoutUtils.createViewGetters(AnnotationLayoutUtils.java:360)
	at org.xtendroid.adapter.AndroidViewHolderProcessor.doTransform(AndroidViewHolderProcessor.java:201)
	at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
```

**Comment by Buggaboo** [comment]
Uhoh. Do you have a snippet of the culprit?

**Comment by svenefftinge** [comment]
FWIW you should never look up types through Class.forname within annotation processing. The classpath is different to the one of the currently processed file.
Use methods from org.eclipse.xtend.lib.macro.services.GlobalTypeLookup instead which is implemented by the passed context (e.g. TransformationContext)

**Comment by tobykurien** [comment]
@svenefftinge thanks for the tip, I'll give that a go
